#!/bin/bash

FILENAME="log_data.txt"

echo "Creating file: $FILENAME"
echo "Timestamp: $(date)" > $FILENAME
echo "This is a log file generated by my script." >> $FILENAME

echo "Done! Check the file using 'cat $FILENAME'"
